---
- name: Install Libvirt/Qemu/etc (Ubuntu)
  block:
    - name: Install packages
      become: yes
      apt:
        update_cache: yes
        state: present
        name: "{{ item }}"
      loop:
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils
        - virt-manager

    - name: "Adding user to libvirt/qemu groups"
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        groups: "{{ item }}"
        append: yes
      loop:
        - libvirt
        - libvirt-qemu
        - kvm
  when: ansible_distribution == "Ubuntu"

- name: Install Libvirt/Qemu/etc (Arch)
  block:
    - name: Install packages
      become: yes
      apt:
        update_cache: yes
        state: present
        name: "{{ item }}"
      loop:
        - libvirt
        - ebtables
        - dnsmasq
        - bridge-utils
        - openbsd-netcat

    - name: "Adding user to libvirt/qemu groups"
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: "{{ item }}"
        append: yes
      loop:
        - libvirt
        - kvm
  when: ansible_os_family == "ArchLinux"

- name: Enable and start libvirtd
  systemd:
    name: libvirtd.service
    state: started
    enabled: True
